Machine learning >>> fichier dataset fusion TMDB OMDB

In [10]:
import pandas as pd
import os

In [11]:
fichier_ML= pd.read_csv("dataset_C_Filtre_1.csv")

In [12]:
fichier_ML.head()

,Title,title,original_title,Genre,genres,Runtime,runtime,Director,Writer_1,Actors_1,...,imdbID,genre_principal,production_companies_names,genre_1,genre_2,genre_3,genre_4,genre_5,genre_6,genre_7
0,Avatar,Avatar,Avatar,"Action, Adventure, Fantasy","[{'id': 878, 'name': 'Science-Fiction'}, {'id'...",162.0,166.0,James Cameron,James Cameron,Sam Worthington,...,tt0499549,Science-Fiction,Dune Entertainment,Science-Fiction,Action,Aventure,NaN,NaN,NaN,NaN
1,Pirates of the Caribbean: At World's End,Pirates des Caraïbes : Jusqu'au bout du monde,Pirates of the Caribbean: At World's End,"Action, Adventure, Fantasy","[{'id': 12, 'name': 'Aventure'}, {'id': 14, 'n...",169.0,168.0,Gore Verbinski,Ted Elliott,Johnny Depp,...,tt0449088,Aventure,Jerry Bruckheimer Films,Aventure,Fantastique,Action,NaN,NaN,NaN,NaN
2,Spectre,Spectre,Spectre,"Action, Adventure, Thriller","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",148.0,148.0,Sam Mendes,John Logan,Daniel Craig,...,tt2379713,Action,Metro-Goldwyn-Mayer,Action,Aventure,Thriller,NaN,NaN,NaN,NaN
3,The Dark Knight Rises,The Dark Knight Rises,The Dark Knight Rises,"Action, Crime, Drama","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",164.0,164.0,Christopher Nolan,Jonathan Nolan,Christian Bale,...,tt1345836,Action,Syncopy,Action,Crime,Drame,Thriller,NaN,NaN,NaN
4,John Carter,John Carter,John Carter,"Action, Adventure, Sci-Fi","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",132.0,140.0,Andrew Stanton,Andrew Stanton,Taylor Kitsch,...,tt0401729,Action,Walt Disney Pictures,Action,Aventure,Science-Fiction,NaN,NaN,NaN,NaN

In [13]:
fichier_ML.columns

Index(['Title', 'title', 'original_title', 'Genre', 'genres', 'Runtime',
       'runtime', 'Director', 'Writer_1', 'Actors_1', 'Actors_2', 'Actors_3',
       'Year', 'release_date', 'Oscars_Gagnés', 'Oscars_nommés',
       'Recompenses_globales', 'Ratings', 'imdbRating', 'imdbVotes',
       'vote_average', 'vote_count', 'popularity', 'Rated', 'Type', 'Plot',
       'tagline', 'overview', 'budget', 'revenue', 'origin_country',
       'original_language', 'spoken_languages', 'backdrop_path', 'poster_path',
       'production_companies', 'production_countries',
       'belongs_to_collection.name', 'id', 'imdb_id', 'imdbID',
       'genre_principal', 'production_companies_names', 'genre_1', 'genre_2',
       'genre_3', 'genre_4', 'genre_5', 'genre_6', 'genre_7'],
      dtype='str')

In [14]:
ex_Ml=fichier_ML[["title","genre_principal","runtime","imdbRating"]]

In [15]:
ex_Ml

,title,genre_principal,runtime,imdbRating
0,Avatar,Science-Fiction,166.0,7.9
1,Pirates des Caraïbes : Jusqu'au bout du monde,Aventure,168.0,7.1
2,Spectre,Action,148.0,6.8
3,The Dark Knight Rises,Action,164.0,8.4
4,John Carter,Action,140.0,6.6
...,...,...,...,...
4328,Trucker,Drame,90.0,6.5
4329,Me You and Five Bucks,Romance,93.0,5.6
4330,The Lords of Salem,Horreur,96.0,5.2
4331,Housebound,Horreur,111.0,6.7
4332,Wal-Mart: The High Cost of Low Price,Documentaire,98.0,6.8

In [16]:
from sklearn.metrics.pairwise import cosine_similarity #  pour mesurer la similarité entre films
import numpy as np

In [17]:
#encodage des données genres principales
genre_encode =pd.get_dummies(ex_Ml["genre_principal"])

In [18]:
ex_Ml = pd.concat([ex_Ml,genre_encode],axis=1).drop(columns="genre_principal")

In [19]:
#suppresion de la colonne genre_principal

ex_Ml.drop(["genre_principal"],axis=1,inplace=True)

KeyError: "['genre_principal'] not found in axis"

In [25]:
ex_Ml.head()

,runtime,imdbRating,Action,Animation,Aventure,Comédie,Crime,Documentaire,Drame,Familial,Fantastique,Guerre,Histoire,Horreur,Musique,Mystère,Romance,Science-Fiction,Thriller,Western
0,166.0,7.9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,168.0,7.1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,148.0,6.8,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,164.0,8.4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,140.0,6.6,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [47]:
ex_Ml.to_csv("ex_Ml&.csv",index=False)

In [8]:
import streamlit as st
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import requests
import json

In [ ]:

st.title('Bienvenue sur Netflox')
st.image('https://media1.tenor.com/m/Hh5lO8fCAAIAAAAC/netflix.gif', caption='Netflix')




df = ex_Ml.copy() #remplacement  du fichier github par dataset TMDB+ IMDB

movie_name="title"

st.dataframe(df.head())

choix = st.selectbox(
    "Choisi un film et je te proposerai des recommandation qui te plairont :-)",
    df[movie_name])




st.write("Ton choix :", choix)

try:
    infosDuFilm = json.loads(requests.get(f"http://www.omdbapi.com/?apikey=548c959e&t={choix}").text)
    image = infosDuFilm["Poster"]
    st.image(image)
except:
    st.image("https://media.tenor.com/5SSLJ7zpa7EAAAAM/asd.gif")

nn = NearestNeighbors(n_neighbors=6, metric="euclidean")

X = df.drop(columns=movie_name)
#équivalent_de : 
X = df.drop(movie_name, axis=1)
y = df[movie_name]

#Clustering, donc pas de y
nn.fit(X)

#On récupère les caractéristiques du film choisie par l'utilisateur
numeroDelaLigne = df[df[movie_name] == choix].index[0]

#On récupère toutes les colonnes features du film ayant l'index du choix
featuresAPredire = X.iloc[numeroDelaLigne, :]

#featuresAPredire = df.iloc[numeroDelaLigne, :].drop(columns="movie_name")

#st.write(featuresAPredire)

distances, index = nn.kneighbors([featuresAPredire])

listeDesRecommandations = df[movie_name][index[0]]

st.write(distances)
st.write(index)
st.write(listeDesRecommandations.values)

st.write(listeDesRecommandations.values[1:])

2026-05-07 19:48:50.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:50.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.029 Session state does not function when running a script without `streamlit run`
2026-05-07 19:48:51.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
c:\Users\momo_\Documents\Projet Juin\mon_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
2026-05-07 19:48:51.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.432 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-07 19:48:51.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [29]:
ex_Ml.to_csv("ex_Ml_encoded.csv",index=False)

In [28]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=6, metric="euclidean")
X = ex_Ml.drop(columns="title")
nn.fit(X)

# Tester avec Avatar
choix = "Avatar"
idx = ex_Ml[ex_Ml["title"] == choix].index[0]
distances, index = nn.kneighbors([X.iloc[idx]])

print("Recommandations pour", choix, ":")
print(ex_Ml["title"].iloc[index[0]].values[1:])

Recommandations pour Avatar :
<ArrowStringArray>
['L'Étrange Histoire de Benjamin Button',
        'Il était une fois dans l'Ouest',
                               'Boyhood',
                               'Solaris',
                              'Scarface']
Length: 5, dtype: str

c:\Users\momo_\Documents\Projet Juin\mon_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(